name: 'Build and Publish'
on:
  push:
jobs:
  build:
    concurrency:
      group: ${{ github.event_name }}-${{ ( github.ref_name == 'main' ) && github.sha || github.ref_name }}-build
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get branch name
        id: main_check
        run: |
          if [ "${GITHUB_REF#refs/heads/}" == "main" ]; then
            IS_MAIN=true
          else
            IS_MAIN=false
          fi
          echo "IS_MAIN=$IS_MAIN" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:test
          tags: ghcr.io/${{ github.repository }}:test
          target: build
          platforms: linux/amd64

      - run: |
          docker run \
            -v ${PWD}/tests:/app/tests \
            -v ${PWD}/src:/app/src \
            -v ${PWD}/eslint.config.js:/app/eslint.config.js \
            ghcr.io/${{ github.repository }}:test yarn run lint
      - run: |
          docker run \
            -v ${PWD}/tests:/app/tests \
            -v ${PWD}/src:/app/src \
            -v ${PWD}/jest.config.ts:/app/jest.config.ts \
            -v ${PWD}/tsconfig.build.json:/app/tsconfig.build.json \
            -v ${PWD}/tsconfig.json:/app/tsconfig.json \
            ghcr.io/${{ github.repository }}:test yarn test

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ghcr.io/${{ github.repository }}:latest

      - name: Push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: ${{ steps.main_check.outputs.IS_MAIN }}
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64
          labels: |
            ${{ steps.meta.outputs.labels }}
