name: 'Build and Publish'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get branch name
        run: |
          if [ "${GITHUB_REF#refs/heads/}" == "main" ]; then
            IS_MAIN=true
          else
            IS_MAIN=false
          fi
          echo "IS_MAIN=$IS_MAIN" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ env.IS_MAIN }}
          tags: phyzical/sonarrtube

      # - name: Test
      #   run: |
      #     echo "Testing..."
      #     docker run phyzical/discord-ai-bot --entrypoint "npm run test"

      # - name: Publish
      #   run: |
      #     echo "TODO extract build from image and publish"
