name: 'Build and Publish'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get branch name
        id: main_check
        run: |
          if [ "${GITHUB_REF#refs/heads/}" == "main" ]; then
            IS_MAIN=true
          else
            IS_MAIN=false
          fi
          echo "IS_MAIN=$IS_MAIN" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          push: false
          tags: ghcr.io/phyzical/sonarrtube:latest
          platforms: linux/amd64,linux/arm64

      - run: docker run ghcr.io/phyzical/sonarrtube:latest "yarn run test"

      - name: Push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          push: ${{ steps.main_check.outputs.IS_MAIN }}
          tags: ghcr.io/phyzical/sonarrtube:latest
          platforms: linux/amd64,linux/arm64
