name: 'Renovate Dependency Check'
on:
  workflow_dispatch:
    inputs:
      forceRecreate:
        description: 'If you should crecreate all prs (this is break glass)'
        type: boolean
        required: false
        default: false
      logLevel:
        description: 'Log level'
        type: choice
        default: 'info'
        options:
          - info
          - debug
  schedule:
    - cron: '0 */12 * * *'
jobs:
  renovate:
    permissions:
      id-token: write
      contents: write
      statuses: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: vars
        id: vars
        run: |
          RECREATE_PRS=$([ "${{ inputs.forceRecreate }}" == "true" ] && echo "always" || echo "auto")
          echo "RECREATE_PRS=$RECREATE_PRS" >> $GITHUB_OUTPUT

          LOG_LEVEL=$([ "${{ inputs.logLevel }}" == "" ] && echo "info" || echo "${{ inputs.logLevel }}")
          echo "LOG_LEVEL=$LOG_LEVEL" >> $GITHUB_OUTPUT

      - name: Renovate
        uses: renovatebot/github-action@7d358366277001f3316d7fa54ff49a81c0158948 # v40.1.7
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
        env:
          LOG_LEVEL: '${{ steps.vars.outputs.LOG_LEVEL }}'
          RENOVATE_RECREATE_WHEN: '${{ steps.vars.outputs.RECREATE_PRS }}'
          RENOVATE_REPOSITORIES: 'phyzical/sonarrtube'
